### ISSUE TITLE
Is there any possible to take a color video?

### ISSUE THREAD

**Issue by meesokim** [obstruse/pico-composite8#1]
Obstruse, Very nice work!
Is there any possibility to make a color rather then gray?
Is it impossible or difficult as your opinion?

Thank you in advance.

**Comment by obstruse** [comment]
Difficult to do with composite video, since you need to modulate a 3.58 MHz color carrier.  Here it's done on an ESP32:
https://bitluni.net/esp32-color-pal
https://github.com/marciot/ESP32CompositeColorVideo 

Easier to do with VGA.  Various methods available, this outputs RGB555: 
https://picockpit.com/raspberry-pi/raspberry-pi-pico-video-output/ 
https://github.com/raspberrypi/pico-playground

Then there's DVI, which pushes the limits of the Pico:
https://github.com/Wren6991/picodvi

But none of them can actually do 8-bit gray :)
